-- Read-only audit: which tables that the Alembic migrations create are absent from the live database?
-- Run in the Supabase SQL editor for project embvfponjxejbtrkryzs, or through a read-only connector.
-- Names come from create_table() calls in alembic/versions at master on 2026-10-05. A table that a later
-- migration dropped (for example healing_proposals) can show as missing. Judge each one before acting.
BEGIN READ ONLY;
SET LOCAL statement_timeout = '10s';
SET LOCAL lock_timeout = '1s';
WITH expected(relation_name) AS (
  SELECT unnest(ARRAY[
    'agent_memories',
    'ai_estimation_feedback',
    'arcs',
    'asset_collections',
    'assets',
    'batch_queue',
    'bds_sessions',
    'beats',
    'brainstorm_sessions',
    'champion_states',
    'chapters',
    'character_knowledge',
    'characters',
    'chunks',
    'cloud_image_control_receipts',
    'cloud_image_events',
    'cloud_image_idempotency_bindings',
    'cloud_image_jobs',
    'cloud_image_leases',
    'cloud_image_operation_receipts',
    'cloud_image_outbox',
    'cloud_image_protected_requests',
    'cloud_image_stage_attempts',
    'collab_rooms',
    'collab_snapshots',
    'collab_tokens',
    'collection_assets',
    'compression_dictionaries',
    'consistency_alerts',
    'context_packs',
    'cost_ledger',
    'covers',
    'cssa_authorization_consumptions',
    'cssa_counters',
    'cssa_quota_reservations',
    'detected_anomalies',
    'df_rf_dispositions',
    'df_rf_evidence_links',
    'df_rf_finding_candidates',
    'diligence_findings',
    'diligence_projects',
    'diligence_reviews',
    'document_tags',
    'documents',
    'domains',
    'evaluation_metrics',
    'events',
    'execution_experiences',
    'execution_index',
    'factions',
    'global_rate_limits',
    'governed_broadcasts',
    'healing_proposals',
    'inferences',
    'jobs',
    'journeys',
    'language_preferences',
    'llm_intel_drift_reports',
    'llm_intel_extracted_claims',
    'llm_intel_pending_candidates',
    'llm_intel_promoted_records',
    'llm_intel_promotion_decisions',
    'llm_intel_receipts',
    'llm_intel_replay_manifests',
    'llm_intel_source_fingerprints',
    'llm_intel_supersession_chains',
    'llm_policy_bandit_states',
    'llm_policy_envelopes',
    'llm_policy_reward_records',
    'llm_policy_run_finalizations',
    'llm_policy_run_ledger',
    'locations',
    'lore_edges',
    'lore_entities',
    'lore_pins',
    'manuscripts',
    'map_edge_modifiers',
    'map_edges',
    'map_nodes',
    'map_regions',
    'memory_claims',
    'memory_conflicts',
    'memory_deletions',
    'memory_episodes',
    'memory_facts',
    'memory_receipts',
    'metric_baselines',
    'model_catalog',
    'model_metrics',
    'model_outcomes',
    'model_performance',
    'model_results',
    'pf_agent_logs',
    'pf_ai_audit_log',
    'pf_automation_alerts',
    'pf_automation_jobs',
    'pf_automation_overrides',
    'pf_automation_runs',
    'pf_campaign_outcomes',
    'pf_campaigns',
    'pf_coverage',
    'pf_domain_reputation',
    'pf_evidence_items',
    'pf_geo_probe_templates',
    'pf_geo_probes',
    'pf_journalists',
    'pf_match_results',
    'pf_outreach_events',
    'pf_pitches',
    'pf_prompt_packs',
    'pf_provider_configs',
    'pf_retrieval_runs',
    'pf_social_draftsets',
    'planning_model_performance',
    'planning_outcomes',
    'pricing_alerts',
    'pricing_monitor_runs',
    'pricing_snapshots',
    'project_genres',
    'project_sessions',
    'projects',
    'ps_cloud_intake_records',
    'ps_cloud_receipts',
    'rate_card_snapshots',
    'routing_decisions',
    'run_evidence',
    'runs',
    'runtime_promotion_approval_decisions',
    'runtime_promotion_candidate_decisions',
    'runtime_promotion_candidates',
    'runtime_promotion_execution_requests',
    'runtime_promotion_execution_statuses',
    'runtime_promotion_receipts',
    'runtime_promotion_verification_results',
    'scenes',
    'sentinel_healing_events',
    'sentinel_sweeps',
    'skill_nominations',
    'stack_outcomes',
    'story_arcs',
    'style_profiles',
    'supabase_log_events',
    'tags',
    'tarcie_events',
    'team_insights',
    'team_invites',
    'team_learning_aggregates',
    'team_members',
    'team_projects',
    'teams',
    'users',
    'vibeforge_projects'
  ])
)
SELECT e.relation_name,
       to_regclass('public.' || e.relation_name) IS NOT NULL AS present_in_public,
       (SELECT count(*) FROM pg_catalog.pg_class c
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = e.relation_name AND n.nspname <> 'public') AS copies_in_other_schemas,
       e.relation_name LIKE 'runtime_promotion%' AS runtime_promotion_family
FROM expected e
WHERE to_regclass('public.' || e.relation_name) IS NULL
ORDER BY runtime_promotion_family DESC, e.relation_name;
-- Also report the recorded revisions.
SELECT version_num FROM public.alembic_version;
ROLLBACK;
