"""
Load testing suite using Locust.
Tests API performance under high concurrency and sustained load.

Installation:
    pip install locust

Usage:
    locust -f tests/load/locustfile.py --host=http://localhost:8001
    
    Then open http://localhost:8089 in browser to control the test.
    
    Or run headless:
    locust -f tests/load/locustfile.py --host=http://localhost:8001 \
        -u 100 -r 10 --run-time 5m --headless
"""

import time
from locust import HttpUser, task, between, TaskSet, events, constant
from locust.contrib.fasthttp import FastHttpUser
import json
import random
import string
from datetime import datetime


class APITaskSet(TaskSet):
    """Task set for API load testing."""
    
    def on_start(self):
        """Setup for each user - register and authenticate."""
        # Generate unique credentials
        self.username = f"loadtest_{int(time.time()*1000)}_{random.randint(0, 9999)}"
        self.email = f"{self.username}@loadtest.local"
        self.password = "LoadTestPass123!"
        self.token = None
        
        # Register user
        self.client.post(
            "/api/auth/register",
            json={
                "email": self.email,
                "username": self.username,
                "password": self.password
            },
            name="/api/auth/register"
        )
        
        # Login and get token
        response = self.client.post(
            "/api/auth/login",
            json={
                "username": self.username,
                "password": self.password
            },
            name="/api/auth/login"
        )
        
        if response.status_code == 200:
            self.token = response.json().get("access_token")
        
        self.headers = {"Authorization": f"Bearer {self.token}"} if self.token else {}
        self.project_ids = []
        self.diligence_ids = []
    
    @task(30)  # 30% weight - most common operation
    def get_projects(self):
        """Get list of projects."""
        self.client.get(
            "/api/projects",
            headers=self.headers,
            name="/api/projects [GET]"
        )
    
    @task(20)  # 20% weight
    def create_project(self):
        """Create a new project."""
        project_data = {
            "name": f"Load Test Project {int(time.time()*1000)}",
            "industry": random.choice(["Technology", "Healthcare", "Finance", "Energy"]),
            "stage": random.choice(["Seed", "Series A", "Series B", "Series C"]),
            "description": "Generated by load test"
        }
        
        response = self.client.post(
            "/api/projects",
            json=project_data,
            headers=self.headers,
            name="/api/projects [POST]"
        )
        
        if response.status_code == 200:
            project_id = response.json().get("id")
            if project_id:
                self.project_ids.append(project_id)
    
    @task(10)  # 10% weight
    def get_single_project(self):
        """Get single project details."""
        if self.project_ids:
            project_id = random.choice(self.project_ids)
            self.client.get(
                f"/api/projects/{project_id}",
                headers=self.headers,
                name="/api/projects/{id} [GET]"
            )
    
    @task(10)  # 10% weight
    def update_project(self):
        """Update a project."""
        if self.project_ids:
            project_id = random.choice(self.project_ids)
            update_data = {
                "description": f"Updated at {datetime.now().isoformat()}"
            }
            
            self.client.put(
                f"/api/projects/{project_id}",
                json=update_data,
                headers=self.headers,
                name="/api/projects/{id} [PUT]"
            )
    
    @task(15)  # 15% weight
    def search_projects(self):
        """Search for projects."""
        search_terms = ["tech", "ai", "data", "test", "load"]
        query = random.choice(search_terms)
        
        self.client.get(
            f"/api/search?q={query}",
            headers=self.headers,
            name="/api/search [GET]"
        )
    
    @task(8)  # 8% weight
    def create_diligence(self):
        """Create due diligence review."""
        if self.project_ids:
            project_id = random.choice(self.project_ids)
            diligence_data = {
                "project_id": project_id,
                "review_type": random.choice(["technical", "financial", "comprehensive"]),
                "scope": "Load test review"
            }
            
            response = self.client.post(
                "/api/diligence",
                json=diligence_data,
                headers=self.headers,
                name="/api/diligence [POST]"
            )
            
            if response.status_code == 200:
                diligence_id = response.json().get("id")
                if diligence_id:
                    self.diligence_ids.append(diligence_id)
    
    @task(5)  # 5% weight
    def add_finding(self):
        """Add finding to diligence review."""
        if self.diligence_ids:
            diligence_id = random.choice(self.diligence_ids)
            finding_data = {
                "title": f"Finding {int(time.time()*1000)}",
                "category": random.choice(["Financial", "Technical", "Legal", "Team"]),
                "severity": random.choice(["info", "low", "medium", "high", "critical"]),
                "status": "open",
                "description": "Auto-generated finding from load test"
            }
            
            self.client.post(
                f"/api/diligence/{diligence_id}/findings",
                json=finding_data,
                headers=self.headers,
                name="/api/diligence/{id}/findings [POST]"
            )
    
    @task(2)  # 2% weight - health check
    def health_check(self):
        """Health check endpoint."""
        self.client.get(
            "/health",
            name="/health [GET]"
        )


class APIUser(HttpUser):
    """
    Simulates a normal user using the API.
    Each user will execute tasks from APITaskSet.
    """
    tasks = [APITaskSet]
    wait_time = between(1, 3)  # Wait 1-3 seconds between tasks


class FastAPIUser(FastHttpUser):
    """
    Simulates fast API users with optimized HTTP client.
    Use this for high-concurrency scenarios.
    """
    tasks = [APITaskSet]
    wait_time = between(0.5, 1.5)
    connection_pool_size = 10


# Event handlers for reporting
@events.test_start.add_listener
def on_test_start(environment, **kwargs):
    """Called when test starts."""
    print("\n" + "="*50)
    print("LOAD TEST STARTED")
    print(f"Start time: {datetime.now().isoformat()}")
    print("="*50 + "\n")


@events.test_stop.add_listener
def on_test_stop(environment, **kwargs):
    """Called when test stops."""
    print("\n" + "="*50)
    print("LOAD TEST COMPLETED")
    print(f"Stop time: {datetime.now().isoformat()}")
    print("="*50 + "\n")
    
    # Print stats
    print("\nRequest Statistics:")
    print(f"{'Endpoint':<40} {'Requests':<12} {'Failures':<12} {'Avg (ms)':<12}")
    print("-" * 76)
    
    for endpoint, stats in environment.stats.entries.items():
        avg_time = stats.avg_response_time if stats.num_requests > 0 else 0
        print(f"{endpoint[1]:<40} {stats.num_requests:<12} "
              f"{stats.num_failures:<12} {avg_time:<12.0f}")


@events.request.add_listener
def on_request(request_type, name, response_time, response_length, exception, **kwargs):
    """Called for each request."""
    if exception:
        print(f"❌ {name}: {exception}")
    elif response_time > 1000:
        print(f"⚠️  SLOW: {name} took {response_time:.0f}ms")


# Performance benchmarks
BENCHMARKS = {
    "GET /api/projects": {"max_response_time": 500, "max_failure_rate": 0.01},
    "POST /api/projects": {"max_response_time": 1000, "max_failure_rate": 0.05},
    "POST /api/diligence": {"max_response_time": 1000, "max_failure_rate": 0.05},
    "GET /api/search": {"max_response_time": 2000, "max_failure_rate": 0.05},
    "GET /health": {"max_response_time": 200, "max_failure_rate": 0.01},
}


@events.test_stop.add_listener
def check_benchmarks(environment, **kwargs):
    """Check if performance meets benchmarks."""
    print("\n" + "="*50)
    print("PERFORMANCE BENCHMARK RESULTS")
    print("="*50 + "\n")
    
    failed_benchmarks = []
    
    for endpoint, stats in environment.stats.entries.items():
        endpoint_name = endpoint[1]
        
        # Find matching benchmark
        benchmark = None
        for bench_name, bench_config in BENCHMARKS.items():
            if bench_name in endpoint_name:
                benchmark = bench_config
                break
        
        if not benchmark:
            continue
        
        # Check response time
        avg_time = stats.avg_response_time if stats.num_requests > 0 else 0
        max_allowed = benchmark["max_response_time"]
        
        if avg_time > max_allowed:
            failed_benchmarks.append(
                f"❌ {endpoint_name}: avg {avg_time:.0f}ms > {max_allowed}ms"
            )
        else:
            print(f"✅ {endpoint_name}: avg {avg_time:.0f}ms <= {max_allowed}ms")
        
        # Check failure rate
        failure_rate = stats.num_failures / stats.num_requests if stats.num_requests > 0 else 0
        max_failure_rate = benchmark["max_failure_rate"]
        
        if failure_rate > max_failure_rate:
            failed_benchmarks.append(
                f"❌ {endpoint_name}: failure rate {failure_rate:.2%} > {max_failure_rate:.2%}"
            )
        else:
            print(f"✅ {endpoint_name}: failure rate {failure_rate:.2%} <= {max_failure_rate:.2%}")
    
    if failed_benchmarks:
        print("\n⚠️  FAILED BENCHMARKS:")
        for failure in failed_benchmarks:
            print(f"  {failure}")
    else:
        print("\n✅ All benchmarks passed!")


if __name__ == "__main__":
    print("Load testing suite for DataForge API")
    print("Run with: locust -f tests/load/locustfile.py --host=http://localhost:8001")
