"""
Multi-Provider Pipeline models — model catalog, pricing, cost ledger, batch queue.

Tables:
  - model_catalog: Canonical AI model registry with pricing and capabilities
  - pricing_snapshots: Historical pricing data captured from provider pages
  - pricing_alerts: Price change alerts generated by the pricing monitor
  - pricing_monitor_runs: Pricing monitor execution records
  - cost_ledger: Per-inference cost tracking across all providers
  - batch_queue: Batch inference job queue with lifecycle tracking
"""

from datetime import datetime
from uuid import uuid4

from sqlalchemy import (
    Column, Integer, String, Text, Boolean, ForeignKey,
    DateTime, Float, Numeric, Index, CheckConstraint
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import UUID, JSONB

from app.database import Base


# ── model_catalog ──────────────────────────────────────────────────────

class ModelCatalog(Base):
    __tablename__ = "model_catalog"

    model_key = Column(String(128), primary_key=True)
    provider = Column(String(32), nullable=False, index=True)
    model_id = Column(String(128), nullable=False)
    input_cost_per_mtok = Column(Numeric(10, 4), nullable=False)
    output_cost_per_mtok = Column(Numeric(10, 4), nullable=False)
    batch_input_cost = Column(Numeric(10, 4), nullable=True)
    batch_output_cost = Column(Numeric(10, 4), nullable=True)
    max_context = Column(Integer, nullable=False)
    cache_read_discount = Column(Numeric(4, 2), nullable=False, default=0)
    supports_batch = Column(Boolean, nullable=False, default=False)
    supports_structured_output = Column(Boolean, nullable=False, default=False)
    tier = Column(String(20), nullable=False, index=True)
    is_active = Column(Boolean, nullable=False, default=True)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    updated_by = Column(String(64), nullable=False, default="system")

    __table_args__ = (
        CheckConstraint("tier IN ('budget', 'workhorse', 'flagship')", name="ck_model_catalog_tier"),
        CheckConstraint("input_cost_per_mtok >= 0", name="ck_model_catalog_input_cost"),
        CheckConstraint("output_cost_per_mtok >= 0", name="ck_model_catalog_output_cost"),
    )


# ── pricing_monitor_runs ───────────────────────────────────────────────

class PricingMonitorRun(Base):
    __tablename__ = "pricing_monitor_runs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    trigger_type = Column(String(20), nullable=False)
    status = Column(String(20), nullable=False, default="running", index=True)
    providers_scraped = Column(Integer, nullable=False, default=0)
    models_extracted = Column(Integer, nullable=False, default=0)
    changes_detected = Column(Integer, nullable=False, default=0)
    auto_applied = Column(Integer, nullable=False, default=0)
    alerts_created = Column(Integer, nullable=False, default=0)
    total_cost_usd = Column(Numeric(10, 6), nullable=True)
    error = Column(Text, nullable=True)
    started_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    completed_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    snapshots = relationship("PricingSnapshot", back_populates="run", cascade="all, delete-orphan")
    alerts = relationship("PricingAlert", back_populates="run", cascade="all, delete-orphan")

    __table_args__ = (
        CheckConstraint("trigger_type IN ('scheduled', 'manual')", name="ck_pricing_run_trigger"),
        CheckConstraint("status IN ('running', 'completed', 'failed')", name="ck_pricing_run_status"),
    )


# ── pricing_snapshots ─────────────────────────────────────────────────

class PricingSnapshot(Base):
    __tablename__ = "pricing_snapshots"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    provider = Column(String(32), nullable=False, index=True)
    run_id = Column(UUID(as_uuid=True), ForeignKey("pricing_monitor_runs.id", ondelete="CASCADE"), nullable=False, index=True)
    models = Column(JSONB, nullable=False)
    raw_content_hash = Column(String(64), nullable=True)
    extraction_model = Column(String(128), nullable=True)
    validation_errors = Column(JSONB, nullable=False, default=list)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    run = relationship("PricingMonitorRun", back_populates="snapshots")


# ── pricing_alerts ────────────────────────────────────────────────────

class PricingAlert(Base):
    __tablename__ = "pricing_alerts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    run_id = Column(UUID(as_uuid=True), ForeignKey("pricing_monitor_runs.id", ondelete="CASCADE"), nullable=False, index=True)
    provider = Column(String(32), nullable=False, index=True)
    model_id = Column(String(128), nullable=False)
    change_type = Column(String(20), nullable=False)
    field_changed = Column(String(64), nullable=True)
    old_value = Column(Numeric(10, 4), nullable=True)
    new_value = Column(Numeric(10, 4), nullable=True)
    change_percent = Column(Numeric(6, 2), nullable=True)
    status = Column(String(20), nullable=False, default="pending", index=True)
    resolved_by = Column(String(64), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    admin_notes = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    run = relationship("PricingMonitorRun", back_populates="alerts")

    __table_args__ = (
        CheckConstraint(
            "change_type IN ('price_increase', 'price_decrease', 'new_model', 'model_deprecated', 'capability_change')",
            name="ck_pricing_alert_change_type"
        ),
        CheckConstraint(
            "status IN ('pending', 'applied', 'dismissed', 'investigating')",
            name="ck_pricing_alert_status"
        ),
        Index("ix_pricing_alerts_model", "provider", "model_id"),
    )


# ── cost_ledger ───────────────────────────────────────────────────────

class CostLedger(Base):
    __tablename__ = "cost_ledger"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    user_id = Column(String(128), nullable=True)
    provider = Column(String(32), nullable=False)
    model_id = Column(String(128), nullable=False)
    task_type = Column(String(64), nullable=False)
    input_tokens = Column(Integer, nullable=False)
    output_tokens = Column(Integer, nullable=False)
    input_cost_usd = Column(Numeric(10, 6), nullable=False)
    output_cost_usd = Column(Numeric(10, 6), nullable=False)
    total_cost_usd = Column(Numeric(10, 6), nullable=False)
    is_batch = Column(Boolean, nullable=False, default=False)
    is_cached = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)

    __table_args__ = (
        Index("ix_cost_ledger_period", "user_id", "created_at"),
        Index("ix_cost_ledger_provider", "provider", "created_at"),
        Index("ix_cost_ledger_task", "task_type", "created_at"),
    )


# ── batch_queue ───────────────────────────────────────────────────────

class BatchQueue(Base):
    __tablename__ = "batch_queue"

    id = Column(Integer, primary_key=True, index=True)
    batch_group_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    app_id = Column(String(50), nullable=False)
    task_type = Column(String(50), nullable=False)
    model_key = Column(String(50), nullable=False)
    provider = Column(String(20), nullable=False)

    # Request payload
    messages_json = Column(JSONB, nullable=False)
    max_tokens = Column(Integer, nullable=False)
    temperature = Column(Float, nullable=False, default=0.7)
    structured_output_json = Column(JSONB, nullable=True)

    # Callback metadata
    callback_url = Column(String(500), nullable=True)
    callback_meta = Column(JSONB, nullable=True)

    # Lifecycle
    status = Column(String(20), nullable=False, default="queued", index=True)
    provider_batch_id = Column(String(200), nullable=True)

    # Results
    response_content = Column(Text, nullable=True)
    input_tokens = Column(Integer, nullable=True)
    output_tokens = Column(Integer, nullable=True)
    cost_usd = Column(Numeric(10, 6), nullable=True)

    # Timing
    queued_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    submitted_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)

    # Error handling
    error_message = Column(Text, nullable=True)
    retry_count = Column(Integer, nullable=False, default=0)

    __table_args__ = (
        CheckConstraint("status IN ('queued', 'submitted', 'completed', 'failed')", name="ck_batch_queue_status"),
        Index("ix_batch_queue_provider_status", "provider", "status"),
    )
